[package]
name = "quanta-index-contract"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[features]
quanta-native-identity-v1 = ["quanta-index-contract-base/quanta-native-identity-v1"]

[dependencies]
ciborium = { workspace = true }
imbl = { workspace = true }
memchr = { workspace = true }
quanta-index-contract-base = { version = "0.1.0", path = "../quanta-index-contract-base" }
quanta-index-lq-norm = { version = "0.1.0", path = "../quanta-index-lq-norm" }
serde = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
proptest = { workspace = true }
