[package]
name = "quanta-index-lq-semantic"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ciborium = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
ciborium = { workspace = true }
proptest = { workspace = true }
