[package]
name = "quanta-index-lq-norm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ciborium = { workspace = true }
quanta-index-lq-text-normalizer = { version = "0.1.0", path = "../quanta-index-lq-text-normalizer" }
regex-syntax = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "pipeline"
harness = false
