[package]
name = "quanta-index-searchd"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
quanta-index-contract = { version = "0.1.0", path = "../quanta-index-contract" }
quanta-index-control-sqlite = { version = "0.1.0", path = "../quanta-index-control-sqlite" }
quanta-index-core = { version = "0.1.0", path = "../quanta-index-core" }

[dev-dependencies]
tempfile.workspace = true
