[package]
name = "quanta-index-searchd"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
quanta-index-contract = { version = "0.1.0", path = "../quanta-index-contract" }
quanta-index-control = { version = "0.1.0", path = "../quanta-index-control" }
quanta-index-core = { version = "0.1.0", path = "../quanta-index-core" }
quanta-index-ipc = { version = "0.1.0", path = "../quanta-index-ipc" }
quanta-index-lexical = { version = "0.1.0", path = "../quanta-index-lexical" }
quanta-index-semantic = { version = "0.1.0", path = "../quanta-index-semantic" }
sha2.workspace = true
tantivy = { workspace = true }
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
