#!/usr/bin/env python3
"""
prompt-manager (pm) — AI agent prompt file management CLI.

SSOT: tools/prompt-manager/
  sources/   — edit here only
  templates/ — Jinja2 templates per agent
  targets.yaml — source → output mapping

Commands:
  sync    [--target NAME] [--dry-run]   Render & write all (or one) target files
  lint    [--target NAME]               Drift check — exit 1 if out of sync (CI gate)
  status                                Show sync status of all targets
  preview --target NAME [--section N]  Print rendered output to stdout
  list                                  List all configured targets
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT = Path(__file__).parent.parent.parent.resolve()  # repo root
PM_DIR = Path(__file__).parent.resolve()
TARGETS_FILE = PM_DIR / "targets.yaml"
TEMPLATES_DIR = PM_DIR / "templates"
SOURCES_DIR = PM_DIR / "sources"

GENERATED_BANNER = """\
<!-- =========================================================
     DO NOT EDIT — generated by tools/prompt-manager/pm.py
     Edit sources in: tools/prompt-manager/sources/
     Then re-run:     python tools/prompt-manager/pm.py sync
     ========================================================= -->
"""

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class Target:
    name: str
    output: Path
    template: Path
    description: str
    sections: list[Path] = field(default_factory=list)

    @classmethod
    def from_dict(cls, name: str, d: dict) -> Target:
        # template value may be "templates/foo.j2" or just "foo.j2"
        tmpl_val = d["template"]
        tmpl_path = PM_DIR / tmpl_val  # always relative to pm dir
        return cls(
            name=name,
            output=ROOT / d["output"],
            template=tmpl_path,
            description=d.get("description", ""),
            # targets.yaml uses "sources/foo/bar.md" paths relative to PM_DIR
            # strip leading "sources/" so paths resolve under SOURCES_DIR
            sections=[
                SOURCES_DIR / (s[len("sources/") :] if s.startswith("sources/") else s)
                for s in d.get("sections", [])
            ],
        )


def load_targets(names: list[str] | None = None) -> list[Target]:
    raw = yaml.safe_load(TARGETS_FILE.read_text())
    targets = [Target.from_dict(k, v) for k, v in raw["targets"].items()]
    if names:
        targets = [t for t in targets if t.name in names]
        missing = set(names) - {t.name for t in targets}
        if missing:
            die(f"Unknown target(s): {', '.join(sorted(missing))}")
    return targets


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render(target: Target) -> str:
    """Render a target to a string using its Jinja2 template + sources."""
    if not target.template.exists():
        die(f"Template not found: {target.template}")

    # Load section content
    sections: dict[str, str] = {}
    for sec_path in target.sections:
        if not sec_path.exists():
            die(f"Source section not found: {sec_path}")
        key = sec_path.relative_to(SOURCES_DIR).as_posix()
        sections[key] = sec_path.read_text()

    env = Environment(
        loader=FileSystemLoader(str(target.template.parent)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    tmpl = env.get_template(target.template.name)
    body = tmpl.render(sections=sections, target=target)

    return (GENERATED_BANNER + body).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_sync(args: argparse.Namespace) -> int:
    targets = load_targets([args.target] if args.target else None)
    changed = []
    skipped = []
    errors = []

    for t in targets:
        try:
            rendered = render(t)
            current = t.output.read_text() if t.output.exists() else None

            if current == rendered:
                skipped.append(t.name)
                continue

            if args.dry_run:
                print(f"  [dry-run] would update: {t.output.relative_to(ROOT)}")
                changed.append(t.name)
                continue

            t.output.parent.mkdir(parents=True, exist_ok=True)
            t.output.write_text(rendered)
            changed.append(t.name)
            print(f"  ✓ synced: {t.output.relative_to(ROOT)}")
        except Exception as e:
            errors.append((t.name, str(e)))
            print(f"  ✗ error [{t.name}]: {e}", file=sys.stderr)

    print()
    if changed:
        print(f"Updated ({len(changed)}): {', '.join(changed)}")
    if skipped:
        print(f"Already up-to-date ({len(skipped)}): {', '.join(skipped)}")
    if errors:
        print(f"Errors ({len(errors)}): {', '.join(n for n, _ in errors)}", file=sys.stderr)
        return 1
    return 0


def cmd_lint(args: argparse.Namespace) -> int:
    targets = load_targets([args.target] if args.target else None)
    drift: list[tuple[str, str]] = []

    for t in targets:
        try:
            rendered = render(t)
            current = t.output.read_text() if t.output.exists() else None

            if current != rendered:
                rel = t.output.relative_to(ROOT)
                if current is None:
                    reason = "file does not exist"
                else:
                    # Show a compact diff summary
                    cur_lines = current.splitlines()
                    new_lines = rendered.splitlines()
                    added = sum(1 for line in new_lines if line not in cur_lines)
                    removed = sum(1 for line in cur_lines if line not in new_lines)
                    reason = f"+{added}/-{removed} lines differ"
                drift.append((t.name, f"{rel} — {reason}"))
        except Exception as e:
            drift.append((t.name, f"render error: {e}"))

    if drift:
        print("✗ prompt-manager drift detected — run: python tools/prompt-manager/pm.py sync\n")
        for name, detail in drift:
            print(f"  [{name}] {detail}")
        print()
        return 1

    print(f"✓ all {len(targets)} target(s) in sync")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    targets = load_targets()
    rows = []

    for t in targets:
        try:
            rendered = render(t)
            current = t.output.read_text() if t.output.exists() else None
            if not t.output.exists():
                status = "MISSING"
            elif current == rendered:
                status = "OK"
            else:
                status = "DRIFT"
            size = f"{len(rendered.splitlines())} lines"
        except Exception as e:
            status = f"ERROR: {e}"
            size = "-"

        rows.append((t.name, status, str(t.output.relative_to(ROOT)), size))

    # Pretty print
    col_w = [
        max(len(r[i]) for r in rows + [("target", "status", "output", "size")]) for i in range(4)
    ]
    header = "  ".join(h.ljust(w) for h, w in zip(["TARGET", "STATUS", "OUTPUT", "SIZE"], col_w))
    print(header)
    print("-" * len(header))
    for row in rows:
        line = "  ".join(v.ljust(w) for v, w in zip(row, col_w))
        if row[1] == "DRIFT":
            print(f"\033[33m{line}\033[0m")  # yellow
        elif row[1] == "MISSING":
            print(f"\033[31m{line}\033[0m")  # red
        elif row[1] == "OK":
            print(f"\033[32m{line}\033[0m")  # green
        else:
            print(line)
    return 0


def cmd_preview(args: argparse.Namespace) -> int:
    if not args.target:
        die("--target is required for preview")
    targets = load_targets([args.target])
    rendered = render(targets[0])

    if args.section:
        # Print only the Nth section (1-indexed)
        lines = rendered.splitlines(keepends=True)
        # Find section headers (## or ###)
        headers = [
            (i, line)
            for i, line in enumerate(lines)
            if line.startswith("## ") or line.startswith("# ")
        ]
        idx = args.section - 1
        if idx < 0 or idx >= len(headers):
            die(f"Section {args.section} out of range (1–{len(headers)})")
        start = headers[idx][0]
        end = headers[idx + 1][0] if idx + 1 < len(headers) else len(lines)
        print("".join(lines[start:end]), end="")
    else:
        print(rendered, end="")
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    targets = load_targets()
    for t in targets:
        print(f"  {t.name:<20} → {t.output.relative_to(ROOT)}")
        if t.description:
            print(f"  {'':20}   {t.description}")
        src_list = ", ".join(p.relative_to(SOURCES_DIR).as_posix() for p in t.sections)
        print(f"  {'':20}   sources: {src_list}")
        print()
    return 0


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def die(msg: str) -> None:
    print(f"pm: error: {msg}", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="pm",
        description=textwrap.dedent("""\
            prompt-manager — AI agent prompt file management CLI
            SSOT: tools/prompt-manager/sources/
        """),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="command", required=True)

    # sync
    s = sub.add_parser("sync", help="Render & write all (or one) target files")
    s.add_argument("--target", metavar="NAME", help="Sync a specific target only")
    s.add_argument("--dry-run", action="store_true", help="Show what would change without writing")

    # lint
    lint_parser = sub.add_parser("lint", help="Drift check — exit 1 if out of sync (CI gate)")
    lint_parser.add_argument("--target", metavar="NAME", help="Check a specific target only")

    # status
    sub.add_parser("status", help="Show sync status of all targets")

    # preview
    pv = sub.add_parser("preview", help="Print rendered output to stdout")
    pv.add_argument("--target", metavar="NAME", required=True)
    pv.add_argument("--section", metavar="N", type=int, help="Print only section N (1-indexed)")

    # list
    sub.add_parser("list", help="List all configured targets")

    return p


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    dispatch = {
        "sync": cmd_sync,
        "lint": cmd_lint,
        "status": cmd_status,
        "preview": cmd_preview,
        "list": cmd_list,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
