[package]
name = "quanta-index-control-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
quanta-index-contract = { version = "0.1.0", path = "../quanta-index-contract" }
quanta-index-core = { version = "0.1.0", path = "../quanta-index-core" }
rusqlite.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
