//! Typed error codes the readiness authorities emit.

pub(crate) const ERR_SEMANTIC_GENERATION_NOT_MATERIALIZED: &str =
    "SEMANTIC_GENERATION_NOT_MATERIALIZED";
pub(crate) const ERR_SEMANTIC_GENERATION_NOT_SEALED: &str = "SEMANTIC_GENERATION_NOT_SEALED";
pub(crate) const ERR_SEMANTIC_MANIFEST_DIGEST_MISMATCH: &str = "SEMANTIC_MANIFEST_DIGEST_MISMATCH";
pub(crate) const ERR_SEARCH_TRACK_GENERATION_NOT_SEALED: &str =
    "SEARCH_TRACK_GENERATION_NOT_SEALED";
pub(crate) const ERR_SEARCH_TRACK_MANIFEST_DIGEST_MISMATCH: &str =
    "SEARCH_TRACK_MANIFEST_DIGEST_MISMATCH";
pub(crate) const ERR_ROLLBACK_CAS_CONFLICT: &str = "ROLLBACK_CAS_CONFLICT";
pub(crate) const ERR_SEARCH_CORPUS_AUTHORITY_CONFLICT: &str = "SEARCH_CORPUS_AUTHORITY_CONFLICT";
pub(crate) const ERR_COMPOSITE_ACTIVATION_CAS_CONFLICT: &str = "COMPOSITE_ACTIVATION_CAS_CONFLICT";
pub(crate) const ERR_RUNTIME_CATALOG_STALE_BATCH: &str = "RUNTIME_CATALOG_STALE_BATCH";
pub(crate) const ERR_RUNTIME_CATALOG_CONFLICTING_BATCH: &str = "RUNTIME_CATALOG_CONFLICTING_BATCH";
pub(crate) const ERR_RUNTIME_CATALOG_UNKNOWN_DOC_ID: &str = "RUNTIME_CATALOG_UNKNOWN_DOC_ID";
pub(crate) const ERR_RUNTIME_CATALOG_CHUNK_UNIVERSE_UNAVAILABLE: &str =
    "RUNTIME_CATALOG_CHUNK_UNIVERSE_UNAVAILABLE";
