[package]
name = "quanta-index-lq-structural"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ciborium = { workspace = true }
quanta-index-contract = { version = "0.1.0", path = "../quanta-index-contract" }
quanta-index-lq-regex = { version = "0.1.0", path = "../quanta-index-lq-regex" }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
